// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhABxyBSAc-v3niBcf_XdFwAE6Om0f9U',
    appId: '1:330351253512:web:07d1b466e85b8832db19bd',
    messagingSenderId: '330351253512',
    projectId: 'ntiproject-87b14',
    authDomain: 'ntiproject-87b14.firebaseapp.com',
    storageBucket: 'ntiproject-87b14.firebasestorage.app',
    measurementId: 'G-WJQ2EV1X0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcepK7niG2QOepXaNENeV2S3Q06TYmBC8',
    appId: '1:330351253512:android:13d5fa9456279b24db19bd',
    messagingSenderId: '330351253512',
    projectId: 'ntiproject-87b14',
    storageBucket: 'ntiproject-87b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5JsulkwmZgjAA-NJ-bpwt5MVPbjotJQI',
    appId: '1:330351253512:ios:57c1a532c9456c75db19bd',
    messagingSenderId: '330351253512',
    projectId: 'ntiproject-87b14',
    storageBucket: 'ntiproject-87b14.firebasestorage.app',
    iosBundleId: 'com.example.updatedSmartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5JsulkwmZgjAA-NJ-bpwt5MVPbjotJQI',
    appId: '1:330351253512:ios:57c1a532c9456c75db19bd',
    messagingSenderId: '330351253512',
    projectId: 'ntiproject-87b14',
    storageBucket: 'ntiproject-87b14.firebasestorage.app',
    iosBundleId: 'com.example.updatedSmartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhABxyBSAc-v3niBcf_XdFwAE6Om0f9U',
    appId: '1:330351253512:web:3c6860c205d07c61db19bd',
    messagingSenderId: '330351253512',
    projectId: 'ntiproject-87b14',
    authDomain: 'ntiproject-87b14.firebaseapp.com',
    storageBucket: 'ntiproject-87b14.firebasestorage.app',
    measurementId: 'G-SHMG1628TX',
  );
}
